### ISSUE TITLE
Loss of network connectivity causing Quewatcher to fail

### ISSUE THREAD

**Issue by Jimloe** [Jimloe/ShturmanBOT#2]
Que watcher || Trying again in 30s
Ignoring exception in on_command_error
Traceback (most recent call last):
  File "C:\Users\user\PycharmProjects\ShturmanBOT asyncpraw\bot\DiscordBot.py", line 84, in watchque
    await client.change_presence(activity=activity)
  File "C:\Users\user\PycharmProjects\ShturmanBOT asyncpraw\venv\lib\site-packages\discord\client.py", line 1062, in change_presence
    await self.ws.change_presence(activity=activity, status=status, afk=afk)
  File "C:\Users\user\PycharmProjects\ShturmanBOT asyncpraw\venv\lib\site-packages\discord\gateway.py", line 625, in change_presence
    await self.send(sent)
  File "C:\Users\user\PycharmProjects\ShturmanBOT asyncpraw\venv\lib\site-packages\discord\gateway.py", line 587, in send
    await self.socket.send_str(data)
  File "C:\Users\user\PycharmProjects\ShturmanBOT asyncpraw\venv\lib\site-packages\aiohttp\client_ws.py", line 150, in send_str
    await self._writer.send(data, binary=False, compress=compress)
  File "C:\Users\user\PycharmProjects\ShturmanBOT asyncpraw\venv\lib\site-packages\aiohttp\http_websocket.py", line 687, in send
    await self._send_frame(message, WSMsgType.TEXT, compress)
  File "C:\Users\user\PycharmProjects\ShturmanBOT asyncpraw\venv\lib\site-packages\aiohttp\http_websocket.py", line 598, in _send_frame
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\PycharmProjects\ShturmanBOT asyncpraw\venv\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\user\PycharmProjects\ShturmanBOT asyncpraw\bot\DiscordBot.py", line 103, in watchque
    await client.change_presence(activity=activity)
  File "C:\Users\user\PycharmProjects\ShturmanBOT asyncpraw\venv\lib\site-packages\discord\client.py", line 1062, in change_presence
    await self.ws.change_presence(activity=activity, status=status, afk=afk)
  File "C:\Users\user\PycharmProjects\ShturmanBOT asyncpraw\venv\lib\site-packages\discord\gateway.py", line 625, in change_presence
    await self.send(sent)
  File "C:\Users\user\PycharmProjects\ShturmanBOT asyncpraw\venv\lib\site-packages\discord\gateway.py", line 587, in send
    await self.socket.send_str(data)
  File "C:\Users\user\PycharmProjects\ShturmanBOT asyncpraw\venv\lib\site-packages\aiohttp\client_ws.py", line 150, in send_str
    await self._writer.send(data, binary=False, compress=compress)
  File "C:\Users\user\PycharmProjects\ShturmanBOT asyncpraw\venv\lib\site-packages\aiohttp\http_websocket.py", line 687, in send
    await self._send_frame(message, WSMsgType.TEXT, compress)
  File "C:\Users\user\PycharmProjects\ShturmanBOT asyncpraw\venv\lib\site-packages\aiohttp\http_websocket.py", line 598, in _send_frame
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\user\PycharmProjects\ShturmanBOT asyncpraw\venv\lib\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\user\PycharmProjects\ShturmanBOT asyncpraw\bot\DiscordBot.py", line 371, in on_command_error
    else:
  File "C:\Users\user\PycharmProjects\ShturmanBOT asyncpraw\venv\lib\site-packages\discord\ext\commands\bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\user\PycharmProjects\ShturmanBOT asyncpraw\venv\lib\site-packages\discord\ext\commands\core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\user\PycharmProjects\ShturmanBOT asyncpraw\venv\lib\site-packages\discord\ext\commands\core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: ConnectionResetError: Cannot write to closing transport
Bad scav was submitted

**Comment by Jimloe** [comment]
Already accounting for connectivity to Reddit, but if there's an issue with updating the Discord status, this will occur.  Wrapping the activity status update in a try/except block to fix.

**Comment by Jimloe** [comment]
Closing out issue due to code rewrite
